/* eslint-disable camelcase */
export default {
  t_key_name: 'dotpharma-key-c-u',
  login_api: '/user/login',
  google_auth_api: '/user/googleauth',
  refresh_token_api: '/user/refresh-token',
  admin_login_api: '/user/admin/login',
  signup_api: '/user/signup',
  logout_api: 'user/logout',
  get_all_users_api: '/user/allusers',
  r_psw_rese_api: '/user/request-password-reset',
  r_r_psw_rese_api: '/user/resend-password-reset',
  create_order: '/orders/createorder',
  apply_psw_reset_api: session => `/user/apply-password-reset/${session}`,
  verify_user_api: session => `/user/activateuser/${session}`,
  resend_verification_api: '/user/resendverification',

  cart_api: id => `/cart/${id}`,
  medicines_api: ({ page = 1, limit = 10 }) => `/medicine/getallmedicines?page=${page}&limit=${limit}`,

  my_profile_api: '/user/myprofile',
  doctors_api: '/doctor/findall',
  appointment_api: '/appointments/makeappointment',
  tag_get_api: '/tags/getall',
  create_medicine_api: '/medicine/createnew',
  update_medicine_api: mid => `/medicine/updatemedicine/${mid}`,
  delete_medicine_api: mid => `/medicine/deletemedicine/${mid}`,
  get_pharmacy__api: '/pharmacy/findall',
  create_pharmacy__api: '/pharmacy/createnew',
  delete_pharmacy__api: ph_id => `/pharmacy/deletepharmacy/${ph_id}`,
  update_pharmacy__api: ph_id => `/pharmacy/updatepharmacy/${ph_id}`,
  get_clinics__api: '/clinics/findall',
};
